version: '3.9'

services:
  banco:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banco_container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - banco_network

networks:
  banco_network:
    driver: bridge
