version: '3.8'

services:
  client:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["npm", "start"]  # Certifique-se de que isso corresponde ao script start no package.json
